### ISSUE TITLE
Suppress Log message for BC incorrect length

### ISSUE THREAD

**Issue by Jerbell** [pgpainless/pgpainless#117]
Hi - would it be possible to change the log message in `KeyRingBuilder.java` for the code:
```java
        try {
            pgpKeyPair = ImplementationFactory.getInstance().getPGPKeyPair(type.getAlgorithm(), keyPair, new Date());
        } catch (PGPException e) {
            // When generating EdDSA keys, the private key has an encoding length of 33 instead of 34, which results
            //  in an exception. Therefore we just try again as a workaround.
            LOGGER.log(Level.INFO, "Private key has wrong length. Try again.", e);
            pgpKeyPair = generateKeyPair(spec);
        }
```
from `info` to `debug`?  Or at least drop passing the exception?
To a normal user who sees this:
```
INFO: Private key has wrong length. Try again.                                                                                             
org.bouncycastle.openpgp.PGPException: Exception constructing key                                                                          
        at org.bouncycastle.openpgp.operator.bc.BcPGPKeyConverter.getPrivateKey(Unknown Source)                                            
        at org.pgpainless.implementation.BcImplementationFactory.jceToBcKeyPair(BcImplementationFactory.java:164)                          
        at org.pgpainless.implementation.BcImplementationFactory.getPGPKeyPair(BcImplementationFactory.java:139)                           
        at org.pgpainless.key.generation.KeyRingBuilder.generateKeyPair(KeyRingBuilder.java:488)                                           
        at org.pgpainless.key.generation.KeyRingBuilder$WithAdditionalUserIdOrPassphraseImpl$BuildImpl.build(KeyRingBuilder.java:356)      
        at com.flowcrypt.shared.crypto.Pgp.generateKey(Pgp.kt:385)                                                                         
        at com.flowcrypt.ekm.commands.GenPrivateKeys.processUid(GenPrivateKeys.kt:60)                                                      
        at com.flowcrypt.ekm.commands.GenPrivateKeys.access$processUid(GenPrivateKeys.kt:23)                                               
        at com.flowcrypt.ekm.commands.GenPrivateKeys$genAndStoreForCsvFile$1.accept(GenPrivateKeys.kt:45)                                  
        at com.flowcrypt.ekm.commands.GenPrivateKeys$genAndStoreForCsvFile$1.accept(GenPrivateKeys.kt:23)                                  
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)                                               
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)                                        
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)                                                 
        at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)                                                  
        at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)                                                 
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)                                                       
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)                                      
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)                                                        
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)                                                   
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)                                          
Caused by: java.lang.RuntimeException: private key encoding has incorrect length                                                           
        at org.bouncycastle.crypto.util.PrivateKeyFactory.getRawKey(Unknown Source)                                                        
        at org.bouncycastle.crypto.util.PrivateKeyFactory.createKey(Unknown Source)                                                        
        at org.bouncycastle.openpgp.operator.bc.BcPGPKeyConverter.implGetPrivateKeyPKCS8(Unknown Source)                                   
        ... 20 more     
```
it gives the strong impression something has gone wrong, but you've already got it covered.

**Comment by vanitasvitae** [comment]
Sure I can fix that :)

**Comment by vanitasvitae** [comment]
I opted to INFO-log that key generation failed and that we try again, but move the exception logging into a FINER-log.

**Comment by tomholub** [comment]
I think that's reasonable. Thanks!

**Comment by Jerbell** [comment]
Thanks very much @vanitasvitae !
