### ISSUE TITLE
Handle decryption errors

### ISSUE THREAD

**Issue by DenBond7** [pgpainless/pgpainless#118]
Please look at the following code

```
@Test
    public final void testDecryptionErrorWrongPassphrase() throws PGPException,
            InvalidAlgorithmParameterException, NoSuchAlgorithmException, IOException {
        //generate data for our test
        String senderPassword = "qwerty1234";
        String receiverPassword = "password1234";
        PGPSecretKeyRing senderSecretKeyRing = PGPainless.generateKeyRing()
                .simpleEcKeyRing("sender@pgpainless.test", senderPassword);
        PGPSecretKeyRing receiverSecretKeyRing = PGPainless.generateKeyRing()
                .simpleEcKeyRing("sender@pgpainless.test", receiverPassword);
        byte[] sourceBytes = "Some data".getBytes();

        //encrypt some data
        List<PGPPublicKeyRing> recipientsPubKeys = new ArrayList<>();
        recipientsPubKeys.add(KeyRingUtils.publicKeyRingFrom(senderSecretKeyRing));
        recipientsPubKeys.add(KeyRingUtils.publicKeyRingFrom(receiverSecretKeyRing));

        ByteArrayOutputStream outputStreamForEncryptedSource = new ByteArrayOutputStream();
        EncryptionStream encryptionStream = PGPainless.encryptAndOrSign()
                .onOutputStream(outputStreamForEncryptedSource)
                .toRecipients(new PGPPublicKeyRingCollection(recipientsPubKeys))
                .usingSecureAlgorithms()
                .doNotSign()
                .noArmor();

        Streams.pipeAll(new ByteArrayInputStream(sourceBytes), encryptionStream);
        encryptionStream.close();

        //decrypt encrypted data
        byte[] encryptedBytes = outputStreamForEncryptedSource.toByteArray();

        List<PGPSecretKeyRing> pgpSecretKeyRings = new ArrayList<>();
        pgpSecretKeyRings.add(receiverSecretKeyRing);
        ByteArrayOutputStream outputStreamWithDecryptedData = new ByteArrayOutputStream();
        SecretKeyRingProtector protector = PasswordBasedSecretKeyRingProtector.forKey(
                receiverSecretKeyRing,
                Passphrase.fromPassword(receiverPassword + "wrong") //remove ''wrong" to pass this test
        );
        DecryptionStream decryptionStream = PGPainless.decryptAndOrVerify()
                .onInputStream(new ByteArrayInputStream(encryptedBytes))
                .decryptWith(protector, new PGPSecretKeyRingCollection(pgpSecretKeyRings))
                .doNotVerify()
                .build();
        Streams.pipeAll(decryptionStream, outputStreamWithDecryptedData);

        //compare results
        assertArrayEquals(sourceBytes, outputStreamWithDecryptedData.toByteArray());
    }
```
Here I simulate the decryption of a file. The next line is important

`Passphrase.fromPassword(receiverPassword + "wrong") //remove "wrong" to pass this test`

If I use the wrong `passphrase` I see the following stack trace

```
checksum mismatch at 0 of 20
org.bouncycastle.openpgp.PGPException: checksum mismatch at 0 of 20
	at org.bouncycastle.openpgp.PGPSecretKey.extractKeyData(Unknown Source)
	at org.bouncycastle.openpgp.PGPSecretKey.extractPrivateKey(Unknown Source)
	at org.pgpainless.decryption_verification.DecryptionStreamFactory.decrypt(DecryptionStreamFactory.java:245)
	at org.pgpainless.decryption_verification.DecryptionStreamFactory.processPGPEncryptedDataList(DecryptionStreamFactory.java:156)
	at org.pgpainless.decryption_verification.DecryptionStreamFactory.processPGPPackets(DecryptionStreamFactory.java:137)
	at org.pgpainless.decryption_verification.DecryptionStreamFactory.create(DecryptionStreamFactory.java:125)
	at org.pgpainless.decryption_verification.DecryptionBuilder$BuildImpl.build(DecryptionBuilder.java:222)
	at org.pgpainless.decryption_verification.DecryptionExceptionTests.testDecryptionErrorWrongPassphrase(DecryptionExceptionTests.java:82)

```
Could we handle such errors much gracefully? For example, throw `PGPException("wrong passphrase") `or even better `WrongPassphraseException`.

**Comment by tomholub** [comment]
I'd absolutely like to vouch for this and similar issues - thrown exceptions should be as descriptive as possible. Thank you!

**Comment by vanitasvitae** [comment]
I introduced `WrongPassphraseException` which is now thrown when an incorrect passphrase is used to decrypt a key.
