### ISSUE TITLE
Adding Subkeys to KeyRings

### ISSUE THREAD

**Issue by vanitasvitae** [pgpainless/pgpainless#20]
I'd like to add subKeys (PGPSecretKey) to a PGPSecretKeyRing.

However I'm hitting a wall because `PGPSecretKeyRing.insertSecretKey(secretKeyRing, secretSubKey);` throws an IllegalArgumentException with the reason that only one master key is allowed in a key ring.

I generated the subkey explicitly with the `isMasterKey` boolean flag set to true. However, in the `insertSecretKey` method BC is performing a check on the inserting key to check if it is a master key. This method returns true for my sub key, because the `subSigs` list is null.

I'm not sure why this is the case and how to get it to a non-null value, as the only public constructor does not set the list to a non-null value.

I'm probably just using the BC API wrong, but it will take some more tinkering to find out what exactly I do wrong.

Progress is tracked in the [addSubKeys branch](https://github.com/pgpainless/pgpainless/tree/addSubKeys).

**Comment by vanitasvitae** [comment]
I did some more experimentation:
I created a class PGPPublicKeyConstructor in the `org.bouncycastle.openpgp` package namespace to be able to access the package-level visible constructors. However, trying to access the constructors that way yields a SecurityException:

```
class "org.bouncycastle.openpgp.PGPPublicKeyConstructor"'s signer information does not match signer information of other classes in the same package
java.lang.SecurityException: class "org.bouncycastle.openpgp.PGPPublicKeyConstructor"'s signer information does not match signer information of other classes in the same package
	at java.base/java.lang.ClassLoader.checkCerts(ClassLoader.java:1151)
	at java.base/java.lang.ClassLoader.preDefineClass(ClassLoader.java:906)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1015)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at org.pgpainless.key.modification.KeyRingEditor.addSubKey(KeyRingEditor.java:225)
	at org.pgpainless.key.modification.KeyRingEditor.addSubKey(KeyRingEditor.java:207)
	at org.pgpainless.key.modification.AddSubKeyTest.testAddSubKey(AddSubKeyTest.java:52)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy5.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:118)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:413)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

There must be another way of creating a public key with non-null subSigs.

**Comment by vanitasvitae** [comment]
Another possible way of solving this issue would be to patch BC to either expose [this constructor](https://github.com/bcgit/bc-java/blob/master/pg/src/main/java/org/bouncycastle/openpgp/PGPPublicKey.java#L139), or create another constructor in PGPPublicKey which takes a boolean flag isMasterKey and if this is set to true makes sure to initialize subSigs with an empty list.

**Comment by tomholub** [comment]
You could look into the BC fork that OpenKeychain is using, maybe they have solved some of these issues.

I think it will be inevitable to eventually use a fork of BC, whether that one or our own.

**Comment by vanitasvitae** [comment]
If the OpenKeychain fork has a solution for this we should consider trying to upstream some solution.

**Comment by wiktor-k** [comment]
Yeah, definitely looking at OpenKeychain is a good way to go. Usually it's just wiring the API correctly. Unfortunately the code of OpenKeychain is not that easy to follow as the app logic is intermixed with OpenPGP key operations.

For the record I just tested and adding subkeys through the UI works so they did solve this problem either through API or their fork. I do agree that if it's in the fork it should be upstreamed but my gut feeling is that it's in some weird order of BouncyCastle API calls. (The same reason we need pgpainless - to hide the inner complexity).

Thanks for your work @vanitasvitae!

**Comment by vanitasvitae** [comment]
Bingo! The OpenKeychain fork adds a [handy method](https://github.com/open-keychain/bouncycastle/blob/openkeychain-master-old/pg/src/main/java/org/bouncycastle/openpgp/PGPPublicKey.java#L949) to the PGPPublicKey class that allows to add SubKey binding certificates.

I will contact the OpenKeychain maintainers to ask them if they plan to (allow to) upstream these changes to BC.

**Comment by vanitasvitae** [comment]
I just went ahead and created [a pull request](https://github.com/bcgit/bc-java/pull/830) that will upstream the `addSubkeyBindingCertification()` method.

Depending on how quickly the PR is getting merged and how long it will take for a new release I will think about whether it makes sense to switch to a fork of BC.
I don't think that the OpenKeychain BC fork is available on maven central?
I'd prefer to keep pgpainless "compatible" to vanilla BC in the long run, but we'll see how it goes :)

**Comment by vanitasvitae** [comment]
It appears that BC 1.67 [added native support](https://github.com/bcgit/bc-java/commit/8ff0b3ba07f0bc627469f5d8b28964de709fc426) for adding subkeys to key rings already!

Using that API was pretty easy to get support for adding sub keys into pgpainless :)
