### ISSUE TITLE
PasswordBasedSecretKeyRingProtector.forKey() and ECC keys

### ISSUE THREAD

**Issue by DenBond7** [pgpainless/pgpainless#97]
@vanitasvitae Please look at [this](https://github.com/FlowCrypt/flowcrypt-android/commit/7629f507ca84219bd839d000209e42ab8b7fc3da) test. It works well for RSA keys. But when I use 

```
senderPGPSecretKeyRing = PGPainless.generateKeyRing().simpleEcKeyRing("sender@encrypted.key", SENDER_PASSWORD)
recipientPGPSecretKeyRing = PGPainless.generateKeyRing().simpleEcKeyRing("juliet@encrypted.key", ECEIVER_PASSWORD)
```

I receive the following error

```
org.bouncycastle.openpgp.PGPException: Exception decrypting key

	at org.bouncycastle.openpgp.PGPSecretKey.extractKeyData(Unknown Source)
	at org.bouncycastle.openpgp.PGPSecretKey.extractPrivateKey(Unknown Source)
	at org.pgpainless.decryption_verification.DecryptionStreamFactory.decrypt(DecryptionStreamFactory.java:232)
	at org.pgpainless.decryption_verification.DecryptionStreamFactory.processPGPEncryptedDataList(DecryptionStreamFactory.java:150)
	at org.pgpainless.decryption_verification.DecryptionStreamFactory.processPGPPackets(DecryptionStreamFactory.java:131)
	at org.pgpainless.decryption_verification.DecryptionStreamFactory.create(DecryptionStreamFactory.java:119)
	at org.pgpainless.decryption_verification.DecryptionBuilder$BuildImpl.build(DecryptionBuilder.java:208)
	at com.flowcrypt.email.security.pgp.PgpEncryptTest.decrypt(PgpEncryptTest.kt:74)
	at com.flowcrypt.email.security.pgp.PgpEncryptTest.testEncryptFile(PgpEncryptTest.kt:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
Caused by: java.lang.NullPointerException
	... 35 more
```

It seems that `SecretKeyPassphraseProvider` uses the wrong pub key and returns `null`. 

https://github.com/pgpainless/pgpainless/blob/7bd12fe5d423b8bf4c7d5388870bd06a14829b99/pgpainless-core/src/main/java/org/pgpainless/key/protection/PasswordBasedSecretKeyRingProtector.java#L58

[Here](https://github.com/FlowCrypt/flowcrypt-android/blob/bb4d10493c133a8ec6d78ac0b6a494f62d3f20f1/FlowCrypt/src/test/java/com/flowcrypt/email/security/pgp/PgpEncryptTest.kt#L76) I've modified my code to use an own realization of PasswordBasedSecretKeyRingProtector

```
val protector = PasswordBasedSecretKeyRingProtector(
        KeyRingProtectionSettings.secureDefaultSettings()) { keyId ->
      pgpSecretKeyRing.publicKeys.forEach { publicKey ->
        if (publicKey.keyID == keyId) {
          return@PasswordBasedSecretKeyRingProtector passphrase
        }
      }
      return@PasswordBasedSecretKeyRingProtector null
    }
```

Is that a bug in `PasswordBasedSecretKeyRingProtector.forKey()` or have I missed something?

**Comment by vanitasvitae** [comment]
Ah I think I know what the issue is. Will fix it asap. Unfortunately I do not find much time to code atm.

**Comment by tomholub** [comment]
Thank you!
